# Generated by Django 5.2.6 on 2025-09-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='imagen',
            field=models.ImageField(null=True, upload_to='marca'),
        ),
        migrations.AddField(
            model_name='modelo',
            name='imagen',
            field=models.ImageField(null=True, upload_to='modelo'),
        ),
    ]
