# Generated by Django 5.2.6 on 2025-09-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_marca_imagen_modelo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='cod_marca',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='clase',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='cod_modelo',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='cod_veh',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='imagen',
            field=models.ImageField(null=True, upload_to='modelo '),
        ),
    ]
