# Generated by Django 5.2.6 on 2025-09-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_marca_cod_marca_alter_modelo_clase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='cod_clase',
            field=models.IntegerField(max_length=10),
        ),
    ]
