# Generated by Django 5.2.6 on 2025-09-13 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_clase_cod_clase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='cod_clase',
            field=models.PositiveIntegerField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='cod_marca',
            field=models.IntegerField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modelos', to='inventario.clase'),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='modelo'),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modelos', to='inventario.marca'),
        ),
    ]
