# Generated by Django 5.2.6 on 2025-09-13 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_parte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_elemento', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=150)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elementos', to='inventario.clase')),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elementos', to='inventario.parte')),
            ],
        ),
    ]
