# Generated by Django 5.2.6 on 2025-09-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_elemento'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='elemento'),
        ),
    ]
