# Generated by Django 5.2.6 on 2025-09-14 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_elemento_fecha_creacion_elemento_fecha_modificacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estructura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_pieza', models.CharField(blank=True, max_length=50, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='estructura')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estructuras', to='inventario.clase')),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estructuras', to='inventario.elemento')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estructuras', to='inventario.marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estructuras', to='inventario.modelo')),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estructuras', to='inventario.parte')),
            ],
        ),
    ]
