# Generated by Django 5.2.6 on 2025-09-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_estructura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='cod_marca',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='cod_modelo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='cod_veh',
            field=models.IntegerField(),
        ),
    ]
