# Generated by Django 5.2.6 on 2025-09-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_alter_marca_cod_marca_alter_modelo_cod_modelo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estructura',
            name='cod_veh',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='cod_veh',
            field=models.IntegerField(unique=True),
        ),
    ]
